In [1]:
import numpy as np
import pandas as pd


In [2]:
bd = pd.read_csv('winequality-red.csv',delimiter=';')


In [3]:
bd.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
bd.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [5]:
bd.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

### Linear Regression

In [6]:
X = bd[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

In [7]:
y = bd['quality']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lm = LinearRegression()

In [12]:
lm.fit(X_train, y_train) 

LinearRegression()

In [13]:
print(lm.intercept_)

7.264173100020852


In [14]:
lm.coef_

array([ 3.96044919e-02, -1.16906171e+00, -3.70552205e-01,  1.37597847e-02,
       -1.42327721e+00,  1.26936356e-03, -3.00684052e-03, -3.22174492e+00,
       -4.61644820e-01,  8.33305012e-01,  3.05119495e-01])

In [15]:
X_train.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [16]:
cdf = pd.DataFrame(lm.coef_,X.columns,columns=['Coeff'])

In [17]:
cdf.head()

Coeff
fixed acidity     0.039604
volatile acidity -1.169062
citric acid      -0.370552
residual sugar    0.013760
chlorides        -1.423277

In [18]:
predictions = lm.predict(X_test)

In [19]:
predictions

array([5.03003792, 5.23628062, 5.01246775, 5.81779264, 6.18374528,
       6.49754959, 6.2374725 , 6.05406419, 5.86370041, 5.60421949,
       5.80191677, 5.95606748, 6.20303329, 5.23229355, 5.62643663,
       5.23322573, 6.38035537, 5.2346498 , 5.18749358, 5.47869148,
       5.82249347, 5.62242535, 5.27549582, 5.8020534 , 5.70625604,
       5.15520283, 5.31949683, 5.68635508, 6.50465315, 5.3098149 ,
       5.31131237, 5.18560412, 5.7714925 , 5.37977679, 5.45365799,
       6.5023938 , 5.83699868, 6.27839734, 5.1306076 , 5.09367743,
       6.51828747, 5.23371783, 6.05951077, 5.84732076, 6.2357648 ,
       6.07867179, 5.76120281, 6.5349755 , 4.89118498, 5.5944457 ,
       5.49211822, 5.95135434, 5.4513232 , 5.48167518, 5.55267489,
       6.0593122 , 6.10064314, 5.98966422, 6.60387211, 6.64166157,
       5.06621371, 4.96668505, 5.42191556, 5.52386135, 5.13899293,
       5.62242535, 4.98305001, 5.55517268, 4.95424287, 5.87929407,
       4.95057069, 5.46011101, 6.05274177, 5.73476012, 5.35579

In [20]:
y_test

678     5
1500    5
1457    5
1079    7
909     6
       ..
990     5
1444    6
1202    8
1291    6
500     6
Name: quality, Length: 528, dtype: int64

In [21]:
from sklearn import metrics

In [22]:
metrics.mean_absolute_error(y_test,predictions)

0.5312196051904471

In [23]:
metrics.mean_squared_error(y_test,predictions)

0.49083830035637405

In [24]:
np.sqrt(metrics.mean_squared_error(y_test,predictions))

0.7005985300843658

### Standardizing Feature Variables

In [25]:
from sklearn.preprocessing import StandardScaler
X_features = X
X = StandardScaler().fit_transform(X)

### Decision Tree

In [26]:
from sklearn.metrics import classification_report

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
dt = DecisionTreeClassifier(random_state=1)

In [29]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [30]:
pred = dt.predict(X_test)

In [32]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           3       0.25      0.20      0.22         5
           4       0.07      0.05      0.06        20
           5       0.67      0.65      0.66       230
           6       0.54      0.59      0.56       199
           7       0.48      0.43      0.46        67
           8       0.20      0.14      0.17         7

    accuracy                           0.57       528
   macro avg       0.37      0.35      0.35       528
weighted avg       0.56      0.57      0.56       528



In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
print(confusion_matrix(y_test,pred))

[[  1   3   1   0   0   0]
 [  0   1  14   4   1   0]
 [  3   4 150  67   5   1]
 [  0   4  53 118  22   2]
 [  0   3   7  27  29   1]
 [  0   0   0   3   3   1]]
